/*
@desc  异步返回衬衫的初始选项
@return {Promise}
*/
module.exports = function(){
    return new Promise( (resolve,reject) => {
        resolve({
            hb:{
                front:{
                    value:'SZ'
                },
                back:{
                    value:'SZ'
                }
            },
            button:{
                front:{
                    color:'CS5',
                    value:'YK'
                },
                back:{
                    color:'CS5',
                    value:'YK'
                }
            },
            buttonhode_thread:{
                front:{
                    value:'XZ_MJ_XDw_WLK_KY_SS_Z'
                },
                back:{
                    value:''
                }
            },
            mj:{
                front:{
                    value:'ZMMJ'
                },
                back:{
                    value:''
                }
            },
            pocket:{
                front:{
                    value:'empty'
                },
                back:{
                    value:''
                }
            },
            collar_surface:{
                front:{},
                back:{}
            },
            collar:{
                front:{
                    value:'XFLG'
                },
                back:{
                    value:''
                }
            },
            sleeve:{
                front:{
                    value:'XZ_XZ_CX_Z'
                },
                back:{
                    value:'XZ_XZ_CX_F'
                }
            },
            cuffs:{
                front:{
                    value:'YJ1Y'
                },
                back:{
                    value:'YJ1Y'
                }
            },
            ds:{
                front:{
                    value:'DS_ZM'
                },
                back:{
                    value:'DS_BM'
                }
            },
            fabric:{
                front:{
                    type:'CS',
                    value:'CS5'
                },
                back:{
                    type:'CS',
                    value:'CS5'
                }
            }
        })
    });
}